Vagrant.configure(2) do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.define "ansible"
  config.ssh.insert_key = false

  config.vm.provider "virtualbox"

  config.vm.provision "docker-install", type: "ansible" do |ansible|
    ansible.playbook = "docker-install.yml"
  end

  config.vm.provision "docker-logrotate", type: "ansible" do |ansible|
      ansible.playbook = "docker-logrotate.yml"
  end

  config.vm.provision "docker-log-driver-rotate", type: "ansible" do |ansible|
    ansible.playbook = "docker-log-driver-rotate.yml"
  end
end
